[package]
name = "hy-route"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Hysteria 2 client routing"

[dependencies]
hy-extras = { path = "../hy-extras" }
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true }
socket2 = "0.6"
libc = "0.2"
